default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wolf_api_challenge_development
  username: postgres
  password: 'password'

test:
  <<: *default
  database: wolf_api_challenge_test
  username: postgres
  password: 'password'

production:
  <<: *default
  database: wolf_api_challenge_production
  username: postgres
  password: 'password'

  cache:
    <<: *default
    database: wolf_api_challenge_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: wolf_api_challenge_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: wolf_api_challenge_production_cable
    migrations_paths: db/cable_migrate
