default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["PG_USER"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "password" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>

development:
  <<: *default
  database: wolf_api_challenge_development

test:
  <<: *default
  database: wolf_api_challenge_test

production:
  <<: *default
  database: wolf_api_challenge_production

  cache:
    <<: *default
    database: wolf_api_challenge_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: wolf_api_challenge_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: wolf_api_challenge_production_cable
    migrations_paths: db/cable_migrate
